#!/bin/bash
#SBATCH --job-name ngsRelate_0316   # Job name
#SBATCH -c 4                   # Use n cpu
#SBATCH -t 3-00:00:00             # Time limit hrs:min:sec
#SBATCH --mem-per-cpu 2500
#SBATCH -o ngsRelate_0316.out    # Standard output and error log
#SBATCH --mail-type ALL
#SBATCH --mail-user xhs315@alumni.ku.dk

module load angsd/0.935
module load gcc
module load R/3.6.1

echo -e "START: $(date)"


echo "0316 - first try"
echo "*** *** *** *** ***"

# Read arguments
bamlist=/projects/mjolnir1/people/xhs315/xhs315.xufen/Historical_analysis_2022new/realign/bam.filelist
ids=/projects/mjolnir1/people/xhs315/xhs315.xufen/Historical_analysis_2022new/ANGSD/Relatedness/ids_all.txt
outname=/projects/mjolnir1/people/xhs315/xhs315.xufen/Historical_analysis_2022new/ANGSD/Relatedness/hisnew_reho
trans=1 # can be 0 or 1 # 1 for ancient
MinDepth=6
MaxDepth=135
minind=12

n=16
echo -e "Number of individuals: $n"

# Filters: 
# No sexual chrs, specified by regions_file
# G: No sites with depth under or above 1% and 99% # I will do it using the min/max depth parameters
# Min Depth and Max Depth according to global depth 90% percentile
# No chrs with less than 10kbps

ref=/projects/mjolnir1/people/xhs315/xhs315.xufen/ref_genomes/HeHo/chr_assembly/HeHo_1.0_HiC.fasta
regions_file="/projects/mjolnir1/people/xhs315/xhs315.xufen/ref_genomes/HeHo/chr_assembly/region.txt"

## First we generate a file with allele frequencies (angsdput.mafs.gz) and a file with genotype likelihoods (angsdput.glf.gz).
#.glf.gz generated by -doGlf 3
# Remove read with a flag above 255 (not primary, failure and duplicate reads)
# Remove reads that have multiple best hits. 
# MinDepth: 1% percentile; MaxDepth: 99% percentile.
# minInd: 75% individuals.
# Include only proper pairs (pairs of read with both mates mapped correctly).

echo -e "Calculating Genotypelikelihoods and calling snps"
    
angsd -b $bamlist -GL 2 -domajorminor 1 -snp_pval 1e-6 -domaf 2 -minmaf 0.05 -doGlf 3 \
     -minMapQ 30 -minQ 20 -minInd $minind -noTrans $trans \
     -doCounts 1 -setMinDepth $MinDepth -setMaxDepth $MaxDepth \
     -remove_bads 1 -uniqueOnly 1 -only_proper_pairs 1 \
     -ref $ref -rf $regions_file \
     -nThreads 20 -out $outname


echo -e "zcat"
    
### Then we extract the frequency column from the allele frequency file and remove the header (to make it in the format NgsRelate needs)
zcat $outname.mafs.gz | cut -f6 | sed 1d > $outname.freq

dt=$(date '+%d/%m/%Y %H:%M:%S');

echo "run NgsRelate at $dt"

### run NgsRelate
ngsRelate -g $outname.glf.gz -n $n -f $outname.freq -O $outname.ngsRelate -z $ids -p 20

echo "estimating inbreeding at $dt"

### Estimate Inbreeding
ngsRelate -g $outname.glf.gz -F 1 -f $outname.freq -n $n -O $outname.ngsRelate.inbreeding -p 20 


echo -e "END: $(date)"

echo "0316 - first try"
echo "*** *** *** *** ***"